### ISSUE TITLE
Error when trying to use callback functionality

### ISSUE THREAD

**Issue by ided** [techatspree/jquery-toastmessage-plugin#4]
Error: options.close is not a function
Source File: js/jquery.toastmessage.js
Line: 144

This happens when trying to use a callback from the plugin using the following code as taken from the example file and updated for my requirements.

```
var bup = $.post("softup.asp", {up: "blog"});
$().toastmessage('showToast', {
    sticky   : 'true',
    position : 'top-right',
    type     : 'notice',
    text : 'A New Blog Has Been Published, Please Check The Blog Menu For More Details.',
    close : bup
});
```

From looking at the examples file this is how the example using a call back was called I have tried adding it as a function etc but cant seem to get it to work in anyway.

**Comment by daniel-tonn** [comment]
Hi,

as I see in your example, you are not defining a function:

instead of

var bup = $.post("softup.asp", {up: "blog"});

you should write something like this:

var bup = function () {
  $.post("softup.asp", {up: "blog"});
}

Then it should work .. at least your function should be called.

regards Daniel

**Comment by ided** [comment]
Cheers, I tried this originally and it was giving errors but I discovered the main reason the call didnt seem t be called was due to an incorrect comparrison so I was just coming back to close it and noticed you had beaten me to it.
Thanks for the great plugin and support.
